from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.acl import Acl
    from ..models.ancestry import Ancestry
    from ..models.file_data import FileData
    from ..models.legal import Legal
    from ..models.record_version_meta_item import RecordVersionMetaItem
    from ..models.record_version_tags import RecordVersionTags


T = TypeVar("T", bound="RecordVersion")


@_attrs_define
class RecordVersion:
    """Metadata record

    Attributes:
        kind (str): Kind of data being ingested. Must follow the naming
              convention:data-Partition-Id}:dataset-name}:record-type}:version}. Example: osdu:wks:dataset--
            File.Generic:1.0.0.
        legal (Legal):
        data (FileData): The file data container containing all necessary details of the file record
        acl (Acl):
        id (str | Unset): Unique identifier generated by the system for the file metadata record.
        ancestry (Ancestry | Unset): A named list of entities in the data lake as a dictionary item.
        version (int | Unset): The version number of this OSDU resource; set by the framework. Example:
            1831253916104085.
        meta (list[RecordVersionMetaItem] | Unset):
        tags (RecordVersionTags | Unset):
    """

    kind: str
    legal: Legal
    data: FileData
    acl: Acl
    id: str | Unset = UNSET
    ancestry: Ancestry | Unset = UNSET
    version: int | Unset = UNSET
    meta: list[RecordVersionMetaItem] | Unset = UNSET
    tags: RecordVersionTags | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        kind = self.kind

        legal = self.legal.to_dict()

        data = self.data.to_dict()

        acl = self.acl.to_dict()

        id = self.id

        ancestry: dict[str, Any] | Unset = UNSET
        if not isinstance(self.ancestry, Unset):
            ancestry = self.ancestry.to_dict()

        version = self.version

        meta: list[dict[str, Any]] | Unset = UNSET
        if not isinstance(self.meta, Unset):
            meta = []
            for meta_item_data in self.meta:
                meta_item = meta_item_data.to_dict()
                meta.append(meta_item)

        tags: dict[str, Any] | Unset = UNSET
        if not isinstance(self.tags, Unset):
            tags = self.tags.to_dict()

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "kind": kind,
                "legal": legal,
                "data": data,
                "acl": acl,
            }
        )
        if id is not UNSET:
            field_dict["id"] = id
        if ancestry is not UNSET:
            field_dict["ancestry"] = ancestry
        if version is not UNSET:
            field_dict["version"] = version
        if meta is not UNSET:
            field_dict["meta"] = meta
        if tags is not UNSET:
            field_dict["tags"] = tags

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.acl import Acl
        from ..models.ancestry import Ancestry
        from ..models.file_data import FileData
        from ..models.legal import Legal
        from ..models.record_version_meta_item import RecordVersionMetaItem
        from ..models.record_version_tags import RecordVersionTags

        d = dict(src_dict)
        kind = d.pop("kind")

        legal = Legal.from_dict(d.pop("legal"))

        data = FileData.from_dict(d.pop("data"))

        acl = Acl.from_dict(d.pop("acl"))

        id = d.pop("id", UNSET)

        _ancestry = d.pop("ancestry", UNSET)
        ancestry: Ancestry | Unset
        if isinstance(_ancestry, Unset):
            ancestry = UNSET
        else:
            ancestry = Ancestry.from_dict(_ancestry)

        version = d.pop("version", UNSET)

        _meta = d.pop("meta", UNSET)
        meta: list[RecordVersionMetaItem] | Unset = UNSET
        if _meta is not UNSET:
            meta = []
            for meta_item_data in _meta:
                meta_item = RecordVersionMetaItem.from_dict(meta_item_data)

                meta.append(meta_item)

        _tags = d.pop("tags", UNSET)
        tags: RecordVersionTags | Unset
        if isinstance(_tags, Unset):
            tags = UNSET
        else:
            tags = RecordVersionTags.from_dict(_tags)

        record_version = cls(
            kind=kind,
            legal=legal,
            data=data,
            acl=acl,
            id=id,
            ancestry=ancestry,
            version=version,
            meta=meta,
            tags=tags,
        )

        record_version.additional_properties = d
        return record_version

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
