name: Code scanning

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    # Run every Wednesday at 00:00 UTC.
    - cron: 0 0 * * 3

permissions: {}

jobs:
  github-actions:
    # Scan GitHub Actions workflow files for security vulnerabilities.
    name: GitHub Actions
    permissions:
      contents: read
      actions: read
      security-events: write
    uses: equinor/ops-actions/.github/workflows/zizmor-codeql.yml@8dfda59d14ec91a8727ac64fe60ab51a4b98d03e # v9.35.0
