name: Lint Pull Request

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

permissions: {}

jobs:
  lint-pr:
    name: Lint PR Title
    permissions:
      contents: read
    uses: equinor/ops-actions/.github/workflows/commitlint.yml@6f3c4901194b286f11800f60fc034417e2c8480a # v9.36.0
    with:
      message: ${{ github.event.pull_request.title }}
